import type { BrandKit } from "@/lib/schemas/trial";

/**
 * Pure, deterministic formatter — no LLM involved, so it's safe to run
 * on the client and easy to unit-test. Keeping this separate from the
 * brand-kit agent means the export format can change without touching
 * the agent prompt or schema.
 */
export function brandKitToMarkdown(kit: BrandKit): string {
  const paletteRows = kit.palette
    .map((p) => `| \`${p.hex}\` | ${p.role} | ${p.contrastNote} |`)
    .join("\n");

  return `# Brand Kit

## Tagline
${kit.tagline}

## Palette
| Hex | Role | Contrast note |
|---|---|---|
${paletteRows}

## Type pairing
- **Heading:** ${kit.typePairing.heading}
- **Body:** ${kit.typePairing.body}
- **Rationale:** ${kit.typePairing.rationale}

## Voice rules
${kit.voiceRules.map((r) => `- ${r}`).join("\n")}

---
*Generated by Brand Court. AI-assisted critique with a human approval gate on every revision — see README for the full trial transcript and disclosure.*
`;
}
