import type { BriefInput } from "@/lib/schemas/brief";
import type {
  ProsecutorOutput,
  DefenseOutput,
  JuryOutput,
  JudgeOutput,
  Revision,
} from "@/lib/schemas/trial";
import type { PaletteReport } from "@/lib/checks/contrast";
import type { ChargeTally } from "@/lib/checks/tally";
import { roman } from "@/lib/format/roman";

export type GateStatus = "pending" | "accepted" | "rejected" | "locked";

export type RevisionRecord = {
  revision: Revision;
  status: GateStatus;
};

export type TranscriptInput = {
  caseNumber: string;
  brief: BriefInput;
  evidence: PaletteReport;
  charges: ProsecutorOutput;
  rebuttals: DefenseOutput;
  votes: JuryOutput;
  tally: ChargeTally[];
  verdict: JudgeOutput;
  revisionRecords: RevisionRecord[];
};

const STATUS_LABEL: Record<GateStatus, string> = {
  pending: "Pending",
  accepted: "Approved",
  locked: "Sealed",
  rejected: "Returned",
};

/**
 * Pure, deterministic formatter for the complete trial record — every
 * charge, rebuttal, jury ballot, the tally, the verdict, and the final
 * status of each revision. Distinct from lib/export/markdown.ts, which
 * only exports the finished brand kit: this is the record of how the
 * trial got there, useful even if the user never finalizes a kit.
 */
export function trialTranscriptToMarkdown({
  caseNumber,
  brief,
  evidence,
  charges,
  rebuttals,
  votes,
  tally,
  verdict,
  revisionRecords,
}: TranscriptInput): string {
  const evidenceLines =
    evidence.failures.length === 0
      ? "No WCAG contrast failures found in the submitted palette."
      : evidence.failures.map((f) => `- ${f.pair} — ${f.ratio}:1 (${f.level})`).join("\n");

  const chargesLines = charges.charges
    .map(
      (c, i) =>
        `**Count ${roman(i + 1)}** [${c.category} · ${c.severity}] — ${c.title}\n${c.description}`
    )
    .join("\n\n");

  const rebuttalsLines = rebuttals.rebuttals
    .map((r) => `- ${r.response}${r.concession ? " *(conceded)*" : ""}`)
    .join("\n");

  const votesLines = votes.votes
    .map(
      (v, i) =>
        `**Juror ${roman(i + 1)}** (${v.persona}) — ${v.verdict}\n${v.justification}`
    )
    .join("\n\n");

  const tallyLines = tally
    .map((t) => `- [${t.chargeId}] ${t.sustain} sustain / ${t.dismiss} dismiss → **${t.outcome}**`)
    .join("\n");

  const revisionsLines =
    revisionRecords.length === 0
      ? "_No revisions were ordered._"
      : revisionRecords
          .map(
            ({ revision, status }) =>
              `**${revision.title}** — ${STATUS_LABEL[status]}\n${revision.description}\n${
                revision.before ? `Before: ${revision.before}\n` : ""
              }Ordered: ${revision.after}`
          )
          .join("\n\n");

  return `# Brand Court Trial Transcript

Case No. ${caseNumber}

## The Brief
${brief.brief}
${brief.tagline ? `\nTagline: ${brief.tagline}` : ""}
${brief.paletteHex.length ? `\nPalette: ${brief.paletteHex.join(", ")}` : ""}

## Exhibit A — Deterministic Evidence
${evidenceLines}

## Charges of the Prosecution
${chargesLines}

## Answer of the Defense
${rebuttalsLines}

## Verdict of the Jury
${votesLines}

## Exhibit B — Tally of the Jury
${tallyLines}

## Ruling of the Court
${verdict.verdictSummary}

### Revisions
${revisionsLines}

---
*Generated by Brand Court — an adversarial AI courtroom with a human approval gate on every revision. No data stored server-side.*
`;
}
